apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-mariadb
  name: {{ .Release.Name }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-mariadb
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_CHARACTER_SET
          value: utf8mb4
        - name: MARIADB_COLLATE
          value: utf8mb4_unicode_ci
        - name: MARIADB_DATABASE
          value: bitnami_moodle
        - name: MARIADB_USER
          value: bn_moodle
        image: docker.io/bitnami/mariadb:10.6
        name: mariadb
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: mariadb-data
      restartPolicy: Always
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mariadb-data
status: {}
