apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-mariadb
  name: {{ .Release.Name }}-mariadb
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: {{ .Release.Name }}-mariadb
status:
  loadBalancer: {}
