apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-moodle
  name: {{ .Release.Name }}-moodle
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 8443
  selector:
    io.kompose.service: {{ .Release.Name }}-moodle
status:
  loadBalancer: {}
