apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-moodle
  name: {{ .Release.Name }}-moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-moodle
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-moodle
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MOODLE_DATABASE_HOST
          value: {{ .Release.Name }}-mariadb
        - name: MOODLE_DATABASE_NAME
          value: bitnami_moodle
        - name: MOODLE_DATABASE_PORT_NUMBER
          value: "3306"
        - name: MOODLE_DATABASE_USER
          value: bn_moodle
        - name: MOODLE_USERNAME
          value: {{ .Values.moodle.user }}
        - name: MOODLE_PASSWORD
          value: {{ .Values.moodle.password }}
        - name: MOODLE_SITE_NAME
          value: {{ .Values.moodle.site_name }}
{{- if .Values.moodle.email.active }}
        - name: MOODLE_EMAIL
          value: {{ .Values.moodle.email.address }}
        - name: MOODLE_SMTP_HOST
          value: {{ .Values.moodle.email.SMTP_host }}
        - name: MOODLE_SMTP_PORT
          value: {{ .Values.moodle.email.SMTP_port }}
        - name: MOODLE_SMTP_USER
          value: {{ .Values.moodle.email.SMTP_user }}
        - name: MOODLE_SMTP_PASSWORD
          value: {{ .Values.moodle.email.SMTP_password }}
        - name: MOODLE_SMTP_PROTOCOL
          value: {{ .Values.moodle.email.SMTP_protocol }}
{{- end }}
        image: {{ .Values.moodle.image }}
        name: moodle
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/moodle
          name: moodle-data
        - mountPath: /bitnami/moodledata
          name: moodledata-data
      restartPolicy: Always
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-moodle-data
      - name: moodledata-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-moodledata-data
status: {}
